#ifndef WWU_LDPLAB_RTSCUDA_IMPL_PARTICLE_INTERSECTION_HPP
#define WWU_LDPLAB_RTSCUDA_IMPL_PARTICLE_INTERSECTION_HPP
#ifdef LDPLAB_BUILD_OPTION_ENABLE_RTSCUDA

namespace ldplab
{
    namespace rtscuda
    {

    }
}

#endif
#endif