#ifndef WWU_LDPLAB_RTSCUDA_RAY_TRACING_STEP_HPP
#define WWU_LDPLAB_RTSCUDA_RAY_TRACING_STEP_HPP
#ifdef LDPLAB_BUILD_OPTION_ENABLE_RTSCUDA

namespace ldplab
{
    namespace rtscuda
    {

    }
}

#endif // LDPLAB_BUILD_OPTION_ENABLE_RTSCUDA
#endif // WWU_LDPLAB_RTSCUDA_RAY_TRACING_STEP_HPP