#ifndef WWU_LDPLAB_RTSCUDA_DEFAULT_BOUNDING_VOLUME_INTERSECTION_FACTORIES_HPP
#define WWU_LDPLAB_RTSCUDA_DEFAULT_BOUNDING_VOLUME_INTERSECTION_FACTORIES_HPP
#ifdef LDPLAB_BUILD_OPTION_ENABLE_RTSCUDA

namespace ldplab
{
    namespace rtscuda
    {

    }
}

#endif
#endif